server {
    proxy_connect_timeout 1180s;
    proxy_send_timeout 1180s;
    proxy_read_timeout 1180s;
    fastcgi_send_timeout 1180s;
    fastcgi_read_timeout 1180s;

    server_name php-2026.loc www.php-2026.loc;
    root /var/www/app;

    index index.php;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location ~ [^/]\.php(/|$) {
        fastcgi_pass php-2026_php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;

        internal;
    }

    location ~ \.php$ {
        return 404;
    }

   # add_header 'Access-Control-Allow-Origin' null;
   # add_header 'Access-Control-Allow-Headers' 'Authorization,Accept,Origin,DNT,X-CustomHeader,Keep-Alive,User-Agent,
   # X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Content-Range,Range';
   # add_header 'Access-Control-Allow-Methods' 'GET,POST,OPTIONS,PUT,DELETE,PATCH';


    client_max_body_size 3000m;
    error_log /var/log/nginx/php-2026_error.log;
    access_log /var/log/nginx/php-2026_access.log;
}
