server {
    proxy_connect_timeout 1180s;
    proxy_send_timeout 1180s;
    proxy_read_timeout 1180s;
    fastcgi_send_timeout 1180s;
    fastcgi_read_timeout 1180s;

    server_name php-2026.loc www.php-2026.loc;
    root /var/www/app;

    index index.php;

    location / {
        try_files $uri $uri/ /index.php$is_args$args;
    }

    location ~ \.php$ {
        fastcgi_pass php-2026_php:9000;
        fastcgi_split_path_info ^(.+\.php)(/.*)$;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    client_max_body_size 3000m;
    error_log /var/log/nginx/php-2026_error.log;
    access_log /var/log/nginx/php-2026_access.log;
}
