server {
    # указываем 80 порт для соединения
    listen 80;
    # нужно указать, какому доменному имени принадлежит наш конфиг
    server_name localhost;

    # задаём корневую директорию
    root /data/mysite.local;

    # стартовый файл
    index index.php index.html;

    charset utf-8;

    # Статика — без логов и PHP
    location ~* \.(jpg|jpeg|gif|png|css|js|ico|svg|woff2?)$ {
        access_log off;
        log_not_found off;
        expires 30d;
    }

    # Единая точка входа
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # php-fpm
    location ~ \.php$ {
        try_files $uri =404;

        include fastcgi_params;
        fastcgi_pass app:9000;
        #fastcgi_pass unix:/var/run/php-fpm.sock;
        fastcgi_index index.php;

        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    # Закрываем доступ к .env и скрытым файлам
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
