[global]
error_log = /dev/stderr

[www]
access.log = /dev/stdout

clear_env = no

catch_workers_output = yes
decorate_workers_output = no

user = www-data
group = www-data

listen = 127.0.0.1:9000

listen.owner = www-data
listen.group = www-data

pm = dynamic

pm.max_children = 28

pm.start_servers = 7

pm.min_spare_servers = 7

pm.max_spare_servers = 21

php_value[session.save_handler] = rediscluster
php_value[session.save_path] = "seed[]=redis-node-1:6379&seed[]=redis-node-2:6379&seed[]=redis-node-3:6379&auth=PASSWORD"
php_value[redis.session.locking_enabled] = 1
php_value[redis.session.lock_retries] = 10
php_value[redis.session.lock_wait_time] = 20000