server {
    listen 80;
    server_name localhost;
    root /var/www/html;

    location / {
        index index.php;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        # Передача запроса в PHP-FPM через общий Unix-сокет
        fastcgi_pass unix:/var/run/php/php-fpm.sock;
    }
}

