server {
    listen 80;
    server_name localhost;
    root /var/www/html;
    index index.php;

    # Логирование
    access_log /var/log/angie/access.log;
    error_log /var/log/angie/error.log warn;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Передача PHP-файлов на обработку контейнеру php
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Запрет доступа к .env и другим скрытым файлам
    location ~ /\.(?!well-known).* {
        deny all;
    }
}

